### ISSUE TITLE
Integration with MoveIt

### ISSUE THREAD

**Issue by takayuki5168** [mkrizmancic/franka_gazebo#2]
@mkrizmancic 

Hi. I want to use Panda in gazebo with MoveIt.
For that we have to use joint trajectory controller instead of joint position controller.
I folked this repo and implemented joint trajectory controller and moveit interface.
https://github.com/takayuki5168/franka_gazebo/tree/joint-trajectory-action

Could you merge if I will make this PR?
Please tell me your opinion.

**Comment by mkrizmancic** [comment]
Hi! That sounds great and I would love to merge your changes.

However, as you can see in #1, this package only works with ROS Kinetic and there are newer and better packages for simulating Franka in Gazebo. I have also moved to Melodic some time ago so I don't maintain this one any more. That also means I won't be able to check your work, but I am willing to take your word that everything works fine. If you are planning to continue developing for Kinetic, I could also link your repo in README so others searching for Franka can have your latest code.

Let me know what you think.

**Comment by takayuki5168** [comment]
@mkrizmancic 
Thanks you for your comment! 
I see. Are there any better or newer ros package to simulate Franka in Gazebo?

**Comment by mkrizmancic** [comment]
[This one](https://github.com/erdalpekel/panda_simulation) seems to be quite popular and in active development.

**Comment by takayuki5168** [comment]
@mkrizmancic I see. Then I will use that repository. Thanks a lot.
